config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:index, :new, :create]
  get '/team', to: 'users#team'
  get '/contact', to: 'users#contact'
  post '/new', to: 'users#create'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
	validates :username, presence: true
	validates :email, presence: true
	validates :bio, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def new
  	@user = User.new
  end

  def create

    if params[:user]
      @user = User.new 
      @user.username = params[:user][:username]
      @user.email = params[:user][:email]
      @user.bio = params[:user][:bio]
      @user.save
    else
      @user = User.new 
      @user.username = params['username']
      @user.email = params['email']
      @user.bio = params['bio']
      @user.save
    end

  end

  def team
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ILoVeFoRm</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="#">Bienvenue sur mon super site de Formulaire !</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <div class="navbar-nav">
          <a class="nav-item nav-link active" <%= link_to 'Accueil', '/users' %> <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link active" <%= link_to 'Create a new User', "/users/new" %> <span class="sr-only">(current)</span></a>
          <a class="nav-item nav-link" <%= link_to 'Team', team_path %></a>
          <a class="nav-item nav-link" <%= link_to 'Contact', contact_path %></a>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/users/contact.html.erb
  <html lang="en">
  <head>
    <meta charset="utf-8">

    <title>Contact</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body class="text-center">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      

      <main role="main" class="inner cover">
        <h1 class="cover-heading">Contact</h1>
        <p class="lead">You just need to send an email to arthur.vouloir@gmail.com !</p>
        <p class="lead">
        </p>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Created by <a href="https://github.com/Javibz">Javi</a>, <a href="https://github.com/SAMTHP">Samir</a>, <a href="https://github.com/VAJangoFett">Arthur</a>.</p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/users/create.html.erb
<div class="jumbotron col-offset-4">
  <h1 class="display-3">Bonjour <%=@user.username%></h1>
  <p>Tu as aura l'ID n°<%= @user.id%> </p>
  <p>Date de création : <%= @user.created_at%> </p>

</div>
 <p><%= link_to 'retour', '/users' %></p>

app/views/users/index.html.erb
 <html lang="en">
  <head>
    <meta charset="utf-8">

    <title>Sign In</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">
  </head>

  <body class="text-center">

    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
      

      <main role="main" class="inner cover">
        <h1 class="cover-heading">Sign in</h1>
        <p class="lead">You just need to click to discover a new world !</p>
        <p class="lead">
        	<%= link_to 'Nouveau user', '/users/new' %>
        </p>
      </main>

      <footer class="mastfoot mt-auto">
        <div class="inner">
          <p>Created by <a href="https://github.com/Javibz">Javi</a>, <a href="https://github.com/SAMTHP">Samir</a>, <a href="https://github.com/VAJangoFett">Arthur</a>.</p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/users/new.html.erb
<html>
  <head>
    <title>New user</title>
  </head>
  <body>
	  	
  	<div class="row">

  		<div class="title-css-boots">
		    <h3>Créer un user en mode form_for :</h3>

			  <%= form_for @user, url: {action: "create"}, html: {class: "col-md-12"} do |f| %>
			    <div class="col-md-12">
	          <div class="form-group">
	            <%= f.label "Votre nom"%>
	            <%= f.text_field :username, placeholder: 'Votre nom ici...', class: "form-control" %>
	          </div>

	          <div class="form-group">
	            <%= f.label "Votre email"%>
	            <%= f.text_field :email, placeholder: 'Enter email...', class: "form-control"%>
	            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
	          </div>
			    </div>

		      <div class="col-md-12 form-group">
		        <%= f.label "Votre bio"%>
		        <%= f.text_area :bio, size: "30x3", placeholder: 'Your biography here...', class: "form-control" %>
		      </div>

			    <div class="col-md-12 form-group">
			        <%= f.submit "Valider", class: "btn btn-primary" %>
			    </div>
			  <% end %>
		 	</div>

    	<div class="title-css-boots">
	      <h3>Créer un user en mode form_tag :</h3>


			  <div class="form-row">
					    <%= form_tag("/users", method: :post, class: "col-md-12") do %>
					    <div class="form-group col-md-12">
					      <%= label_tag 'Votre nom' %>
					      <%= text_field_tag 'username', nil, placeholder:'Votre nom ici...', class: "form-control" %>
					    </div>
					    <div class="form-group col-md-12">
					      <%= label_tag 'Votre email' %>
					      <%= text_field_tag 'email', nil, placeholder:'Enter email...',class: "form-control"  %>
					      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
					    </div>
					    <div class="form-group col-md-12">
					      <%= label_tag 'Votre Bio' %>
					      <%= text_area_tag 'bio', nil, placeholder:'Your biography here...', class: "form-control", rows: "3" %>
					    </div>

				      <div class="form-group col-md-12">
				        <%= submit_tag "Valider", class: "btn btn-primary" %>
				      </div>
				      <% end %>
				</div>
			</div>

    	<div class="title-css-boots">
      	<h3>Créer un user en mode html :</h3>

	      <form class="col-md-12" action='/users' method='POST'>
		      <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
		      	<div class="form-row">
		
			      	<div class="form-group col-md-12">

								<div class="form-group">
								  <div class="form-group">
								      <label for="exampleInputEmail1">User name</label>
								      <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Votre nom ici..." name='username'>
								  </div>

							   	<div class="form-group">
							      <label for="exampleInputEmail1">Email address</label>
							      <input type="text" class="form-control" id="exampleInputEmail1" placeholder="Enter email..." name='email'>
							      <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
							    </div>

				          <div class="form-group">
							      <label for="exampleTextarea">Biography</label>
							      <textarea class="form-control" id="exampleTextarea" rows="3" name='bio' placeholder="Your biography here..."></textarea>
							    </div>
				      	</div>
			      	
				      	<div class="form-row">
				      		<div class="form-group col-md-12">
							      <button type="submit" class="btn btn-primary">Valider</button>
						      </div>
						    </div>
						   </div>
				    </div>
	    	</form>
	    </div>

  </body>
</html>

app/views/users/new_form_tag.html.erb
<html>
  <head>
    <title>New user</title>
  </head>
  <body>
    <h1>Créé un user !</h1>

			<%= form_tag('/users', method: :post) do %>

			<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

			<p> Ton user :</p>

						<%=label_tag(:username, 'User name :')%> 
						<%=text_field_tag(:username)%><br/>
						<%=label_tag(:email, 'Email :')%> 
						<%=text_field_tag(:email)%><br/>
						<%=label_tag(:bio, 'Biographie :')%> 
						<%=text_area_tag(:bio) %><br/>

						<%= submit_tag('Enregistrer')%>
			      <%= link_to 'retour', '/users'%>
      <% end %> 
    </form>
  </body>
</html>

app/views/users/team.html.erb
<html>
<head>
	<title>
		Super Team !
	</title>
</head>
<body>

	<div class="row">
		<div class="card" style="width: 30rem;">
		  <div class="card-body">
		    <h5 class="card-title">Javi</h5>
		    <p class="card-text">Passionné de pêche à la carpe, avec quelques sorties en pêche à la ligne.</p>
		    <a href="https://github.com/Javibz" class="btn btn-primary">Visit my github</a>
		  </div>
		</div>

		<div class="card" style="width: 30rem;">
		  <div class="card-body">
		    <h5 class="card-title">Samir</h5>
		    <p class="card-text">Passionné en pétanque sportive et levée de coude pour fléchettes.</p>
		    <a href="https://github.com/SAMTHP" class="btn btn-primary">Visit my github</a>
		  </div>
		</div>

		<div class="card" style="width: 30rem;">
		  <div class="card-body">
		    <h5 class="card-title">Arthur</h5>
		    <p class="card-text">Issue de la grande table ronde Arthur se mêle à la populasse pour réaliser THP.</p>
		    <a href="https://github.com/VAJangoFett" class="btn btn-primary">Visit my github</a>
		  </div>
		</div>
	</div>
</body>
</html>